<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MacroB.FrontEnd\MacroB.FrontEnd.csproj" />
    <ProjectReference Include="..\MacroB.BackEnd\MacroB.BackEnd.csproj" />
  </ItemGroup>

</Project>
