<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Rollomatic.IlMacroB</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hilke.DataStructures.UnionFind" Version="0.1.1" />
  </ItemGroup>

</Project>
